#!/bin/bash
# Author: Irina.Ivanova@nortal.com
# Prints picture of a bug
# v0.1

printf "                                 0       0\n"
printf "                                0         0\n"
printf "                               0           0 \n"
printf "                                0   WWW   0\n"
printf "                   0000          WWWWWWWWW          0000\n"
printf "                       00     WWWWWWWWWWWWWWW     00\n"
printf "                         00 WWWWWWWWWWWWWWWWWWW 00\n"
printf "                           00WWWWWWWWWWWWWWWWW00\n"
printf "                               WWWWWWWWWWWWW\n"
printf "                          XXXXXXXXWWWWWWWXXXXXXXX\n"
printf "           0000          XxxxxxxxxxXWWWXxxxxxxxxxX          0000\n"
printf "              00        XxxxxxxxxxxxxXxxxxxxxxxxxxX        00\n"
printf "               00  0000XxxxxxxxxxxxxxXxxxxxxxxxxxxxX0000  00\n"
printf "                 00   XxxxxxxxxxxxxxxXxxxxxxxxxxxxxxX   00\n"
printf "                     XxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxX\n"
printf "                    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX\n"
printf "                    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX\n"
printf "                    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX\n"
printf "                0000XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX0000\n"
printf "               00   XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX   00\n"
printf "              00    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX    00\n"
printf "              00    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX    00\n"
printf "              00    XxxxxxxxxxxxxxxxxXxxxxxxxxxxxxxxxxX    00\n"
printf "              00       XxxxxxxxxxxxxxXxxxxxxxxxxxxxX       00\n"
printf "              00          XxxxxxxxxxxXxxxxxxxxxxX          00\n"
printf "            000              XxxxxxxxXxxxxxxxX              000\n"
printf "       000000                   XxxxxXxxxxX                   000000\n"
printf "                                    xXx\n"
